### ISSUE TITLE
编译alist出错，之前还出现这个提示

### ISSUE THREAD

**Issue by magi-Z** [gngpp/Actions-OpenWrt#6]
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-drm-i915', which does not exist
make[2]: Entering directory '/home/magi/Actions-OpenWrt/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/magi/Actions-OpenWrt/openwrt/scripts/config'

**Comment by 0x676e67** [comment]
上游在瞎改呢，找骷髅头
